---
 name: Build container workflow

 on:
  workflow_call:

jobs:
  build_n_package:
    name: Container Build
    runs-on: ubuntu-latest

  steps:
    - uses: action/checkout@v3
    - uses: docker/metadata-action@v3
      id: metadata
    - uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: ${{ github.repository_owner }}
        password: ${{ env.ghub_pkg_token }}
    - uses: int128/kaniko-action@v1
      with:
        push: true
        tags: ${{ steps.metadata.outputs.tags }}
        labels: ${{ steps.metadata.outputs.labels }}
        cache: true
        cache-repository: ghcr.io/${{ github.repository }}/cache
